# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  milagro-crypto-js = nodeEnv.buildNodePackage {
    name = "milagro-crypto-js";
    packageName = "milagro-crypto-js";
    version = "0.1.0";
    src = fetchgit {
      url = "https://github.com/apache/incubator-milagro-crypto-js";
      rev = "2fe9ca56dea97bf66721fa1e6114d6208b736d99";
      sha256 = "de5ba685b2ed5ddf941a9e10315ec8c777a57f26e5711f931bf0ccacbad17cf5";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Apache Milagro Crypto JavaScript Library";
      homepage = "https://github.com/apache/incubator-milagro-crypto-js#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
